<a href="https://colab.research.google.com/github/Maryulianti/Cousera/blob/main/Angka%20Acak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
AngkaAcak = np.random.randint(5, 20, size=10)

In [3]:
AngkaAcak

array([12, 14,  6, 10,  9,  7, 17, 11, 10, 17])

In [4]:
median = np.median(AngkaAcak)

In [5]:
median

10.5

In [6]:
AngkaAcak2 = np.random.randint(1, 20, size=10)

In [7]:
AngkaAcak2

array([ 6, 17,  3,  5, 11,  2, 18, 10,  4,  4])

In [8]:
AngkaAcak2.sort()

In [9]:
AngkaAcak2

array([ 2,  3,  4,  4,  5,  6, 10, 11, 17, 18])

In [10]:
Angka = AngkaAcak2.var()

In [11]:
Angka

30.0